CREATE FUNCTION public."Persons Combined Stats"(
    OUT "ID" INTEGER,
    OUT "Person" CHARACTER VARYING,
    OUT "Origin" CHARACTER VARYING,
    OUT "Gender" CHARACTER VARYING,
    OUT "Athenian with Roman Citizenship" BOOLEAN,
    OUT "Family" CHARACTER VARYING,
    OUT "Extended" CHARACTER VARYING,
    OUT "Deme" CHARACTER VARYING,
    OUT "Total Inscriptions" BIGINT,
    OUT "Bases" BIGINT,
    OUT "Buildings/Monuments" BIGINT,
    OUT "Columns/Herms" BIGINT,
    OUT "Stelai" BIGINT,
    OUT "Altars" BIGINT,
    OUT "Other/Fragmented Objects" BIGINT,
    OUT "Dedications" BIGINT,
    OUT "Decrees" BIGINT,
    OUT "Edicts/Regulations" BIGINT,
    OUT "Epistles" BIGINT,
    OUT "Verses" BIGINT,
    OUT "Other/Uncertain Inscriptions" BIGINT,
    OUT "Before the Telesterion" BIGINT,
    OUT "Between the Propylaea" BIGINT,
    OUT "North of the Telesterion" BIGINT,
    OUT "Outer Courtyard" BIGINT,
    OUT "South Wall" BIGINT,
    OUT "Upper Terrace" BIGINT,
    OUT "Mean Inscription Date" NUMERIC,
    OUT "Mean Inscription Date Span" NUMERIC,
    OUT "Mean Inscription Word Count" NUMERIC,
    OUT "Mean Inscription Character Count" NUMERIC,
    OUT "Total Honors" BIGINT,
    OUT "Different Honors" BIGINT,
    OUT "Magistracies" BIGINT,
    OUT "Sacred Offices" BIGINT,
    OUT "Liturgies/Benefactions" BIGINT,
    OUT "Other/Private Honors" BIGINT,
    OUT "Athenian Honors" BIGINT,
    OUT "Roman Honors" BIGINT,
    OUT "Other/Greek Honors" BIGINT,
    OUT "As Institution Honorand" BIGINT,
    OUT "As Institution Non-Honorand" BIGINT,
    OUT "As Public Honorand" BIGINT,
    OUT "As Public Non-Honorand" BIGINT,
    OUT "As Private Honorand" BIGINT,
    OUT "As Private Non-Honorand" BIGINT,
    OUT "As Genos Honorand" BIGINT,
    OUT "As Genos Non-Honorand" BIGINT,
    OUT "As Areopagus Honorand" BIGINT,
    OUT "As Areopagus Non-Honorand" BIGINT,
    OUT "As Boule Honorand" BIGINT,
    OUT "As Boule Non-Honorand" BIGINT,
    OUT "As Demos Honorand" BIGINT,
    OUT "As Demos Non-Honorand" BIGINT,
    OUT "As Eumolpidai Honorand" BIGINT,
    OUT  "As Eumolpidai Non-Honorand" BIGINT,
    OUT "As Kerykes Honorand" BIGINT,
    OUT "As Kerykes Non-Honorand" BIGINT
) RETURNS SETOF record AS
$BODY$
SELECT person."ID" AS "ID",
       person."Person" AS "Person",
       person."Category" AS "Origin",
       person."Gender" AS "Gender",
       (CASE
            WHEN person."Category" = 'Athenian'
                 AND person."Roman Citizen" = TRUE THEN TRUE
            ELSE FALSE
        END) AS "Athenian with Roman Citizenship",
       person."Family" AS "Family",
       person."Extended" AS "Extended",
       person."Deme" AS "Deme",
       COALESCE(inscription_stats."Total Inscriptions", 0) AS "Total Inscriptions",
       COALESCE(inscription_stats."Bases", 0) AS "Bases",
       COALESCE(inscription_stats."Buildings/Monuments", 0) AS "Buildings/Monuments",
       COALESCE(inscription_stats."Columns/Herms", 0) AS "Columns/Herms",
       COALESCE(inscription_stats."Stelai", 0) AS "Stelai",
       COALESCE(inscription_stats."Altars", 0) AS "Altars",
       COALESCE(inscription_stats."Other/Fragmented Objects", 0) AS "Other/Fragmented Objects",
       COALESCE(inscription_stats."Dedications", 0) AS "Dedications",
       COALESCE(inscription_stats."Decrees", 0) AS "Decrees",
       COALESCE(inscription_stats."Edicts/Regulations", 0) AS "Edicts/Regulations",
       COALESCE(inscription_stats."Epistles", 0) AS "Epistles",
       COALESCE(inscription_stats."Verses", 0) AS "Verses",
       COALESCE(inscription_stats."Other/Uncertain Inscriptions", 0) AS "Other/Uncertain Inscriptions",
       COALESCE(inscription_stats."Before the Telesterion", 0) AS "Before the Telesterion",
       COALESCE(inscription_stats."Between the Propylaea", 0) AS "Between the Propylaea",
       COALESCE(inscription_stats."North of the Telesterion", 0) AS "North of the Telesterion",
       COALESCE(inscription_stats."Outer Courtyard", 0) AS "Outer Courtyard",
       COALESCE(inscription_stats."South Wall", 0) AS "South Wall",
       COALESCE(inscription_stats."Upper Terrace", 0) AS "Upper Terrace",
       COALESCE(inscription_stats."Mean Inscription Date", 0) AS "Mean Inscription Date",
       COALESCE(inscription_stats."Mean Inscription Date Span", 0) AS "Mean Inscription Date Span",
       COALESCE(inscription_stats."Mean Inscription Word Count", 0) AS "Mean Inscription Word Count",
       COALESCE(inscription_stats."Mean Inscription Character Count", 0) AS "Mean Inscription Character Count",
       COALESCE(honor_stats."Total Honors", 0) AS "Total Honors",
       COALESCE(honor_stats."Different Honors", 0) AS "Different Honors",
       COALESCE(honor_stats."Magistracies", 0) AS "Magistracies",
       COALESCE(honor_stats."Sacred Offices", 0) AS "Sacred Offices",
       COALESCE(honor_stats."Liturgies/Benefactions", 0) AS "Liturgies/Benefactions",
       COALESCE(honor_stats."Other/Private Honors", 0) AS "Other/Private Honors",
       COALESCE(honor_stats."Athenian Honors", 0) AS "Athenian Honors",
       COALESCE(honor_stats."Roman Honors", 0) AS "Roman Honors",
       COALESCE(honor_stats."Other/Greek Honors", 0) AS "Other/Greek Honors",
       COALESCE(institution_sponsorship_stats."As Institution Honorand", 0) AS "As Institution Honorand",
       COALESCE(institution_sponsorship_stats."As Institution Non-Honorand", 0) AS "As Institution Non-Honorand",
       COALESCE(institution_sponsorship_stats."As Public Honorand", 0) AS "As Public Honorand",
       COALESCE(institution_sponsorship_stats."As Public Non-Honorand", 0) AS "As Public Non-Honorand",
       COALESCE(institution_sponsorship_stats."As Private Honorand", 0) AS "As Private Honorand",
       COALESCE(institution_sponsorship_stats."As Private Non-Honorand", 0) AS "As Private Non-Honorand",
       COALESCE(institution_sponsorship_stats."As Genos Honorand", 0) AS "As Genos Honorand",
       COALESCE(institution_sponsorship_stats."As Genos Non-Honorand", 0) AS "As Genos Non-Honorand",
       COALESCE(institution_sponsorship_stats."As Areopagus Honorand", 0) AS "As Areopagus Honorand",
       COALESCE(institution_sponsorship_stats."As Areopagus Non-Honorand", 0) AS "As Areopagus Non-Honorand",
       COALESCE(institution_sponsorship_stats."As Boule Honorand", 0) AS "As Boule Honorand",
       COALESCE(institution_sponsorship_stats."As Boule Non-Honorand", 0) AS "As Boule Non-Honorand",
       COALESCE(institution_sponsorship_stats."As Demos Honorand", 0) AS "As Demos Honorand",
       COALESCE(institution_sponsorship_stats."As Demos Non-Honorand", 0) AS "As Demos Non-Honorand",
       COALESCE(institution_sponsorship_stats."As Eumolpidai Honorand", 0) AS "As Eumolpidai Honorand",
       COALESCE(institution_sponsorship_stats."As Eumolpidai Non-Honorand", 0) AS "As Eumolpidai Non-Honorand",
       COALESCE(institution_sponsorship_stats."As Kerykes Honorand", 0) AS "As Kerykes Honorand",
       COALESCE(institution_sponsorship_stats."As Kerykes Non-Honorand", 0) AS "As Kerykes Non-Honorand"
FROM public."Person" AS person
LEFT JOIN public."Persons on Inscriptions Stats"() AS inscription_stats ON person."ID" = inscription_stats."Person ID"
LEFT JOIN public."Persons with Honor Stats"() AS honor_stats ON person."ID" = honor_stats."Person ID"
LEFT JOIN public."Persons on Institution Inscriptions Stats"() AS institution_sponsorship_stats ON person."ID" = institution_sponsorship_stats."Person ID"
$BODY$
LANGUAGE sql STABLE NOT LEAKPROOF;
